# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- include "openshell-workspace.validateValues" . }}
{{- if .Values.sandboxServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sandboxServiceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshell-workspace.labels" . | nindent 4 }}
  {{- with .Values.sandboxServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
